import { env } from "cloudflare:test";
import { describe, expect, it } from "vitest";
import { satisfies } from "../src/semver";

// These cases are lifted from the Rust `semver` crate's documented semantics — the crate the client
// audits with. The point of the module is that the registry's "affected / not affected" verdict
// agrees with `noeta audit`, so the examples are pinned here rather than re-derived.
//
// The hand-written cases below are *documentation*: they name the rule each corner pins, in prose a
// reader can follow. The **authority** is the differential at the bottom of this file, which
// replays `semver-vectors.json` — generated by `cargo run -p noeta-pm --example semver_vectors` in
// the language repo, where every expectation is `semver::VersionReq::matches` itself, and copied
// here with the rest of the wire fixtures. Extend the case list THERE, not here: a case invented in
// this file is checked against nothing, which is how this port's differential came to be a sentence
// in a comment describing a binary that existed in neither repo.

describe("caret requirements", () => {
  it("^1.2.3 := >=1.2.3, <2.0.0", () => {
    expect(satisfies("1.2.3", "^1.2.3")).toBe(true);
    expect(satisfies("1.2.4", "^1.2.3")).toBe(true);
    expect(satisfies("1.9.9", "^1.2.3")).toBe(true);
    expect(satisfies("1.2.2", "^1.2.3")).toBe(false);
    expect(satisfies("2.0.0", "^1.2.3")).toBe(false);
  });

  it("treats the minor as the breaking axis below 1.0", () => {
    // ^0.2.3 := >=0.2.3, <0.3.0
    expect(satisfies("0.2.3", "^0.2.3")).toBe(true);
    expect(satisfies("0.2.9", "^0.2.3")).toBe(true);
    expect(satisfies("0.3.0", "^0.2.3")).toBe(false);
    // ^0.0.3 := >=0.0.3, <0.0.4 — every patch is breaking
    expect(satisfies("0.0.3", "^0.0.3")).toBe(true);
    expect(satisfies("0.0.4", "^0.0.3")).toBe(false);
  });

  it("^1 and ^0 widen to the major", () => {
    expect(satisfies("1.9.9", "^1")).toBe(true);
    expect(satisfies("2.0.0", "^1")).toBe(false);
    expect(satisfies("0.9.9", "^0")).toBe(true);
    expect(satisfies("1.0.0", "^0")).toBe(false);
  });

  it("defaults a bare version to caret", () => {
    expect(satisfies("1.9.0", "1.2.3")).toBe(true);
    expect(satisfies("2.0.0", "1.2.3")).toBe(false);
  });
});

describe("tilde requirements", () => {
  it("~1.2.3 := >=1.2.3, <1.3.0", () => {
    expect(satisfies("1.2.3", "~1.2.3")).toBe(true);
    expect(satisfies("1.2.9", "~1.2.3")).toBe(true);
    expect(satisfies("1.3.0", "~1.2.3")).toBe(false);
    expect(satisfies("1.2.2", "~1.2.3")).toBe(false);
  });

  it("~1 := >=1.0.0, <2.0.0", () => {
    expect(satisfies("1.9.9", "~1")).toBe(true);
    expect(satisfies("2.0.0", "~1")).toBe(false);
  });
});

describe("comparators and wildcards", () => {
  it("matches the advisory fixture's range", () => {
    // NOETA-2026-0001 affects ">=1.0.0, <1.2.0"; the fixture's patched release is 1.2.0.
    const req = ">=1.0.0, <1.2.0";
    expect(satisfies("1.0.0", req)).toBe(true);
    expect(satisfies("1.1.9", req)).toBe(true);
    expect(satisfies("1.2.0", req)).toBe(false);
    expect(satisfies("0.9.9", req)).toBe(false);
  });

  it("handles = and the ordering operators", () => {
    expect(satisfies("1.2.3", "=1.2.3")).toBe(true);
    expect(satisfies("1.2.4", "=1.2.3")).toBe(false);
    expect(satisfies("1.3.0", ">1.2.3")).toBe(true);
    expect(satisfies("1.2.3", ">1.2.3")).toBe(false);
    expect(satisfies("1.2.3", "<=1.2.3")).toBe(true);
  });

  it("handles wildcards", () => {
    expect(satisfies("1.5.0", "1.*")).toBe(true);
    expect(satisfies("2.0.0", "1.*")).toBe(false);
    expect(satisfies("1.2.9", "1.2.*")).toBe(true);
    expect(satisfies("1.3.0", "1.2.*")).toBe(false);
    expect(satisfies("1.0.0", "*")).toBe(true);
  });
});

describe("pre-release rules", () => {
  it("only matches a pre-release when a comparator opted into that release line", () => {
    // ^1.2.3 does not match 1.2.4-alpha: the comparator names 1.2.3, not 1.2.4.
    expect(satisfies("1.2.4-alpha", "^1.2.3")).toBe(false);
    // ...but a comparator on the same major.minor.patch with a pre-release does.
    expect(satisfies("1.2.3-beta", ">=1.2.3-alpha, <1.3.0")).toBe(true);
  });

  it("a bare * does not match a pre-release (VersionReq::STAR has no comparators)", () => {
    expect(satisfies("1.0.0-alpha", "*")).toBe(false);
    expect(satisfies("1.0.0", "*")).toBe(true);
  });

  it("orders pre-release identifiers per SemVer §11", () => {
    // numeric < alphanumeric, and a release outranks any pre-release of the same triple
    expect(satisfies("1.0.0", ">1.0.0-alpha")).toBe(true);
    expect(satisfies("1.0.0-alpha.1", ">1.0.0-alpha.1, <1.0.1")).toBe(false);
    expect(satisfies("1.0.0-alpha.2", ">1.0.0-alpha.1, <1.0.1")).toBe(true);
    expect(satisfies("1.0.0-alpha.beta", ">1.0.0-alpha.1, <1.0.1")).toBe(true);
  });
});

describe("unparseable input answers unknown, never false", () => {
  it("returns null rather than guessing", () => {
    expect(satisfies("1.0.0", "not a range")).toBeNull();
    expect(satisfies("1.0.0", "")).toBeNull();
    expect(satisfies("1.0.0", ">=1.0.0,")).toBeNull();
    expect(satisfies("1.0.0", "1.*.3")).toBeNull();
    expect(satisfies("not-a-version", "^1")).toBeNull();
    expect(satisfies("1.0", "^1")).toBeNull();
  });

  it("accepts and ignores build metadata", () => {
    expect(satisfies("1.2.3+build.5", "^1.2.3")).toBe(true);
  });
});

// --- the differential ------------------------------------------------------------------------------
//
// `semver-vectors.json` is generated in the language repo by `cargo run -p noeta-pm --example
// semver_vectors`, where every `expected` is the answer `semver::VersionReq::matches` gave — the
// exact call `noeta audit` makes (`Advisory::affects`). Replaying it here is the only thing that
// makes "this port agrees with the crate" a fact rather than a claim in a comment.
//
// A failure here is not a test-maintenance chore: it means `noeta audit` and this page would give a
// reader different answers about whether a release is affected by an advisory. Fix `src/semver.ts`
// — never the vectors, which are not editable by hand (regenerate them from the example).

interface Vector {
  rule: string;
  version: string;
  req: string;
  /** `semver::VersionReq::matches`, or `null` when either string did not parse. */
  expected: boolean | null;
  /** What `Advisory::affects` returns — the same answer with unknown collapsed to `false`. */
  affects: boolean;
}

describe("differential against semver::VersionReq::matches", () => {
  const raw = env.WIRE_FIXTURES["semver-vectors.json"];
  const vectors: Vector[] = raw === undefined ? [] : JSON.parse(raw).cases;

  it("carries the generated vector file", () => {
    expect(
      raw,
      "no `semver-vectors.json` — re-copy test/fixtures/wire from the language repo (scripts/sync-wire-fixtures.sh)",
    ).toBeTypeOf("string");
    // A truncated or half-copied file must fail loudly rather than silently checking three cases.
    expect(vectors.length, "the vector file is suspiciously short").toBeGreaterThan(50);
  });

  it("agrees with the Rust crate on every generated case", () => {
    const disagreements: string[] = [];
    for (const v of vectors) {
      const actual = satisfies(v.version, v.req);
      if (actual !== v.expected) {
        disagreements.push(
          `${JSON.stringify(v.version)} vs ${JSON.stringify(v.req)}: ` +
            `semver::VersionReq::matches says ${v.expected}, src/semver.ts says ${actual}  [${v.rule}]`,
        );
      }
    }
    expect(
      disagreements,
      `the hand port disagrees with the Rust crate on ${disagreements.length} of ${vectors.length} cases — ` +
        `\`noeta audit\` and this page would contradict each other:\n  ${disagreements.join("\n  ")}`,
    ).toStrictEqual([]);
  });

  it("collapses unknown to `false` exactly where `Advisory::affects` does", () => {
    // The two callers differ deliberately: the client refuses to fabricate a hit from a malformed
    // advisory range, the page refuses to claim "not affected". Pin that the ONLY place they differ
    // is the unknown case — anywhere else would be a real disagreement wearing a null.
    for (const v of vectors) {
      expect(v.affects, `${v.version} vs ${v.req}`).toBe(v.expected === null ? false : v.expected);
    }
  });
});
